### ISSUE TITLE
Question about `require` for other assets and TS

### ISSUE THREAD

**Issue by fullofcaffeine** [gilamran/fullstack-typescript#16]
As I understood, the `require` here: https://github.com/gilamran/fullstack-typescript/blob/master/src/client/components/Home.tsx#L9 is needed because otherwise, the TS compiler complains, right?

Curious though, do you know if there's a way to set it up so that TS is okay with importing other assets using `import`?

Cheers!

**Comment by gilamran** [comment]
WDYM? can you give an example?

**Comment by gilamran** [comment]
bump

**Comment by fullofcaffeine** [comment]
Hi, sorry for the delay.

If you check this link: https://github.com/gilamran/fullstack-typescript/blob/master/src/client/components/Home.tsx#L9, you'll see the following line highlighted:

```
const css = require('./Home.css');
```

I was wondering why it can't be:

```
import css from './Home.css';
```

Thanks!

**Comment by fullofcaffeine** [comment]
bump :)

**Comment by gilamran** [comment]
There's no simple solution for this, you can see a discussion on [stack-overflow](https://stackoverflow.com/questions/41336858/how-to-import-css-modules-with-typescript-react-and-webpack).
If you have an easy solution I would love to hear about it.

Thanks!
