### ISSUE TITLE
ServiceWorker for PWA

### ISSUE THREAD

**Issue by railto** [gilamran/fullstack-typescript#21]
Really love the project and I'm using it as a base for an app that im building, just wondering tho, if anything special needs to be done in order to get a serviceworker working to enable the app as a PWA?

Thanks again

**Comment by gilamran** [comment]
Can you please provide more details on your situation?
Do you have any issues with the stack?
Also, what is the reason to use serviceworker for PWA?

**Comment by railto** [comment]
Hi There,  Apologies, it seems the issue was with the manifest file, just trying to figure out how I can confirgure the manifest with the requirements for pwa as it's built through webpack

**Comment by gilamran** [comment]
What is the issue with the manifest? and what are the requirements of pwa?
I'll need you to give me as must information as possible... I can't help if I don't understand your needs.

**Comment by railto** [comment]
Hi there,

Thanks for replying, I'm going to leave it for now as I wont actually be building the app that I was initially using this for.
