### ISSUE TITLE
UnhandlePromiseRejectionWarning in production build

### ISSUE THREAD

**Issue by bernardnongpoh** [gilamran/fullstack-typescript#25]
The following error triggered on accessing the app after running
npm start     

> fullstack-typescript@1.1.0 start /home/bernard-w/workspace-2019/typescript/SchoolApp
> node index.js

[HPM] Proxy created: /  ->  http://localhost:8086/
App listening on port 3001!
(node:24779) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8086
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
(node:24779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gilamran** [comment]
In order to test production locally, you have to set `NODE_ENV` to `production`. 
Or just run `npm run start:prod`
