### ISSUE TITLE
found 15783 high severity vulnerabilities

### ISSUE THREAD

**Issue by rkristelijn** [gilamran/fullstack-typescript#26]
First of all, thanks for sharing this piece of code.

I love to see there is only one node_modules folder and everything is typescript.
Personally I am interested how POJO's can be shared across the two platforms and not just the typings. 

there seems to be a vulnerability in package-lock.json that can easily be fixed with npm audit fix. I've created a PR to avoid having the message displayed. Oddly it doesn't change package.json itself.

```
found 15783 high severity vulnerabilities in 874284 scanned packages
  run `npm audit fix` to fix 15783 of them.
npm audit
gius@mac~/fullstack-typescript(master)$ npm audit fix
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 10.095s
fixed 15783 of 15783 vulnerabilities in 874284 scanned packages
gius@mac~/fullstack-typescript(master)$ npm i
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.

audited 887085 packages in 5.593s
found 0 vulnerabilities
```

**Comment by gilamran** [comment]
Hi @rkristelijn ,
Thank for the PR, I'll check it soon.

Well, the _only one node_modules_ is not the highlight of `fullstack-typescript`, the separation of the `tsconfig.json` has more power than what one would think... 
One project is intended for the client (Browser) with different capabilities than the other (Nodejs). Just as an example: the fs (file-system) module is usable only when coding on the server side. Having a separated `tsconfig.json` for each target, helps us focus typescript.

About sharing POJO's, I don't see any problem there... did you?
