### ISSUE TITLE
Console error ForwardRef(ButtonBase)

### ISSUE THREAD

**Issue by AdamScura** [gilamran/fullstack-typescript#28]
Seeing the following error when running the project:

Warning: Failed prop type: Invalid prop `component` supplied to `ForwardRef(ButtonBase)`. Expected an element type that can hold a ref. Did you accidentally provide a plain function component instead? For more information see https://material-ui.com/r/caveat-with-refs-guide

![image](https://user-images.githubusercontent.com/10790922/72235413-edd0df00-3586-11ea-83cb-5e8c5a390298.png)

Windows Version 10.0.18362 Build 18362
Chrome Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by gilamran** [comment]
Thanks!
Fixed, and pushed
