### ISSUE TITLE
Error: Cannot find module 'http-proxy-middleware'

### ISSUE THREAD

**Issue by psawaya** [gilamran/fullstack-typescript#33]
First off, thanks for making my new favorite TS/React basecode. 😃

I noticed that you introduced some changes here (https://github.com/gilamran/fullstack-typescript/commit/437d3dd9fe5cddb296015119a33c3e77b6d4b29f#diff-6dd94babe8fde59638632c402ab3f597) which cause my app to fail with (`Error: Cannot find module 'http-proxy-middleware'`) in production unless I make `http-proxy-middleware` a regular (non-devDependency) dependency.

Might be worth fixing -- `http-proxy-middleware` shouldn't be needed in prod environments.

**Comment by gilamran** [comment]
You are correct, 
I'll fix it.
Thanks

**Comment by gilamran** [comment]
Fixed, thanks!

**Comment by gilamran** [comment]
6?
