### ISSUE TITLE
Can't Run it ant get error TypeError: callSite.getFileName is not a function

### ISSUE THREAD

**Issue by coyhom** [gilamran/fullstack-typescript#34]
I  have git cloned this project and npm run install. when I run 'npm run dev' get this error: callSite.getFileName is not a function..........

there is the pic cut；
![image](https://user-images.githubusercontent.com/9114769/88622612-c03c2500-d0d5-11ea-8990-7c858cb0e7ab.png)

**Comment by gilamran** [comment]
What version of `node` are you using? version of `npm`?
I'll need as much information as possible in order to see what's going on in your situation.

**Comment by gilamran** [comment]
Bump

**Comment by gilamran** [comment]
Closing as there's no response
