### ISSUE TITLE
How are you managing to render React in the EJS file?

### ISSUE THREAD

**Issue by raph90** [gilamran/fullstack-typescript#36]
Hi Gil, 

I'm sorry if this is the wrong place to ask - I have some questions about how this repo works. It does work when I clone it, but when I try to create my own with a similar structure I run into some issues. It would be great if you could explain some things for me...

1. When I try to use http-proxy-middleware I keep running into a problem that I've written about [here](https://stackoverflow.com/questions/63505501/types-is-not-using-the-correct-module-typescript-http-proxy-middleware-webpa)

2. How are you managing to load the react app into the EJS file? I can see that all requests to /statics/ are proxied to create-react-app, but in the EJS file itself I can't see anywhere where you're actually calling in the React app that you've made.

It would be great to have some help with this, many thanks

**Comment by gilamran** [comment]
I've answered your question in detail on stackoverflow.
but in short to solve this just add: `"skipLibCheck": true`, to the shared **tsconfig.json**
