### ISSUE TITLE
Cannot read /src/tsconfig.json file error

### ISSUE THREAD

**Issue by Glider-of-chaos** [gilamran/fullstack-typescript#39]
npm run dev
command produces following error:
> error TS5083: Cannot read file '.../fullstack-typescript/src/tsconfig.json'.

I believe dev-server section of the package.json needs path adjustment. I'll submit a pull request with the fix but it's up to you as I'm kinda new to this and not so sure of myself.

**Comment by gilamran** [comment]
Thanks for the fix!
