### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by Danubius1st** [gilamran/fullstack-typescript#64]
There is a way to turn the app into a PWA ?

**Comment by gilamran** [comment]
hmm, why not?

**Comment by Danubius1st** [comment]
I made some attempts but they didn't work (used InjectManifest, but sw fail to register ...)
I just managed to update packages at last version to work with webpack last version.
Any hint ?

**Comment by gilamran** [comment]
I'll need more details...

**Comment by gilamran** [comment]
Where?
I see that you're replying using the email... not sure it works as you expect
