### ISSUE TITLE
Newer Node support - update engines rule

### ISSUE THREAD

**Issue by DTopping256** [gilamran/fullstack-typescript#84]
### Problem

Currently, following the install steps in `README.md` fails with `yarn install` if the current version of Node.JS is newer than major version 18.

As the repo seems to work with Node.JS v20, why not allow newer versions, but keep the minimum allowed version as v18?

### Changes required

Change [package.json line 7](https://github.com/gilamran/fullstack-typescript/blob/master/package.json#L7) to:
```json
{
  "engines": {
    "node": ">18"
  }
}
```

so that it includes newer versions of Node.JS.

Also [nvmrc](https://github.com/gilamran/fullstack-typescript/blob/master/.nvmrc) could be updated too.

```
20
```

**Comment by DTopping256** [comment]
Cheers for the public repo btw. Very helpful for getting up and running fast, and still working great in 2024!
Happy to make update PRs if you would like?

**Comment by gilamran** [comment]
Done
Also upgraded all packages to their latest versions

**Comment by DTopping256** [comment]
Thanks @gilamran!

As I already used your project as template, I thought I'd give dependency upgrades a go and see how they compared to yours.

I think they are mostly the same. But if its of interest to you, I did spot that `@mui/styles` and `@typescript-eslint/*` dependencies are now deprecated.

- https://mui.com/system/styles/api/
- https://typescript-eslint.io/blog/announcing-typescript-eslint-v7/

I've used this [example mui project for vite & typescript](https://github.com/mui/material-ui/tree/next/examples/material-ui-vite-ts) for migration for the Material UI side of things (replacing 
`StylesProvider` from `@mui/styles` with `ThemeProvider` from `@emotion/react`) which seems to work, although I don't think they quite do the same thing. I kept the `eslint` related things mostly the same for now (as VS Code still requires `eslintrc.json` apparently for its tooling and doesn't yet support "flat" eslint config), although I have upgraded `eslint` to v9.

**Comment by gilamran** [comment]
Yea, I didn't want to get into this upgrade. but it's great that you made it.
Can you share what needs to be done to do this upgrade?

**Comment by DTopping256** [comment]
Yeah I'd be happy to. Would it be OK if I had permission to create a PR? And I'll take a look later.

**Comment by gilamran** [comment]
Anyone with read permissions to a repository can create a pull requests...

**Comment by DTopping256** [comment]
Apologies. I had cloned the repo last night and tried to do the original change written above in a new branch and push that thinking that that would work and create a PR.

Sorry for the silly question, I haven't worked with GitHub in a little while, and not on a public project yet.

**Comment by DTopping256** [comment]
I'll sort out a PR later on today. Thanks 😊
